export const LOAD_USER_DETAILS = 'PEOPLE/LOAD_USER_DETAILS'
export const LOAD_USER_DETAILS_SUCCESS = 'PEOPLE/LOAD_USER_DETAILS_SUCCESS'
export const LOAD_USER_DETAILS_FAILURE = 'PEOPLE/LOAD_USER_DETAILS_FAILURE'